version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: "nginx"
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy

  blue-01:
    image: "httpd"
    volumes:
      - ./blue/index.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy

  blue-02:
    image: "httpd"
    volumes:
      - ./blue/index.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy

  red-01:
    image: "httpd"
    volumes:
      - ./red/index.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy

  red-02:
    image: "httpd"
    volumes:
      - ./red/index.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy