version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: "nginx"
    ports:
    - 80:80
    networks:
      - proxy

  blue:
    image: "httpd"
    volumes:
      - ./public.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy

  red:
    image: "httpd"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
    networks:
    - proxy